message = [
    "ATARENIUM (Pythonium) FALCON  v0.93 (Demo)",
    "Ported from Amiga with intention to learn",
    "some Python with Pygame.",
    "Updated 03.04.2021, first release at",
    "Decrunch 2020 gamedev compo (2nd place).",
    "",
    "Luc3k: code & MSX",
    "Softiron: GFX",
    "KaiN, Proxy & PCH: AFK",
    "",
    "Special credit goes to Saberman - ",
    "The Great Atariman of the Galaxy.",
    "",
    "Navigate your ship using",
    "WSAD or arrows.",
    "M - toggle music/sfx/mute in play.",
    "",
    "Look for 3-letter cheatcodes here ",
    "and there and try typing them in menu.", 
    "There is one for unlimited coal,", 
    "one for great-looking ship, and one",
    "for skipping levels by N in play.",
    "(Fire or Return to continue)",
]