page1 = [
    "Captain Tramiel, our planet was attacked by",
    "treacherous Great Miner and his race of",
    "Amigans. Almost all coal supplies for our",
    "Atari are gone.",
    "Renton - Minister of Mining is reporting",
    "that natural coal deposits are almost",
    "depleted and most of our miners fell to a",
    "strange disease and must remain qurantined.",
    "There is nobody left to work in mines.",
    "If we run out of coal for our Ataris we",
    "face the apocalypse of punch out tickets.",
    "Scouting ROBBOts we sent out into space",
    "did not return. ",
    "We need your help Captain Tramiel.",
    "You have to go to Amigans Space Sector",
    "(ASS), retrieve any surviving ROBBOts ",
    "and reclaim our coal supplies. ",
    "Beware of their secret weapon",
    "- 16bit processing power, 32-color graphics",
    "and 4-channel sound.",
    "Don't let them foul you.",
    "",
    "(Press Return...)",
]

page2 = [
    "We are giving you masterpiece of our space",
    "engineery. Our newest spacecraft named",
    "ATARENIUM FALCON. ",
    "Fully automated. The core of the craft is",
    "Atari Falcon running on highly efficient ",
    "eco pea-coal. It is also equipped with",
    "external automated arm.",
    "This is experimental prototype. Now GO!",
    "One more thing Captain... While you traverse",
    "enemy territory try to collect as many",
    "capacitors as you can so the Amigans can't",
    "replace leaking ones in their Amigas.",
    "Let electrolyte eat out their PCBs.",
    "HAR! HAR! HAR!",
    "",
    "(Press Return...)",
]